name: final2

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Make fail if the previous workflow was failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo '::error::Previous workflow was failed'
          exit 1
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_run:
    workflows:
      - final
    branches:
      - '*'
    types:
      - completed